resources:
  repositories:
    - repository: templates
      type: git
      name: devsecops/templates

trigger:
- azure-devops

pool:
  vmImage: ubuntu-latest

steps:
- template: baseline.yml@templates





































# - task: trivy@1
#   inputs:
#     image: moby/buildkit
#     exitCode: 0
#   # continueOnError: true

# - script: |
#     echo "#################"
#     FILES=$(find /tmp/ -name "trivy-results-*.json")
#     echo "#################"
#     echo "##vso[task.setvariable variable=myVar;]$FILES"
#     echo "##vso[task.addattachment type=consolidated-scan-results;name=aqua-scan-results.json;]$FILES"

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: $(myVar)
#     ArtifactName: CodeAnalysisLogs


# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: /home/vsts/work/_temp/gitleaks-scan-results.json
#     ArtifactName: CodeAnalysisLogs

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: $(Build.SourcesDirectory)/checkov-scan-results.sarif
#     ArtifactName: CodeAnalysisLogs

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: $(Build.SourcesDirectory)/checkov-scan-results.json
#     ArtifactName: CodeAnalysisLogs
    
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: $(Build.SourcesDirectory)/intercept-scan-results.sarif
#     ArtifactName: CodeAnalysisLogs
    
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: $(Build.SourcesDirectory)/intercept-scan-results.json
#     ArtifactName: CodeAnalysisLogs
    
  
# - task: azure-pipelines-checkov@1.0.1
#   displayName: Azure Pipeline Checkov Task